'''
This is a collection of all strings in the program.
Every new string comes here.
'''

STRING_TABLE = {
    'Site title': 'Trips organizer',
    'Navbar title': 'Trips organizer',
    'Navbar trips link title' : 'Походы',
    'Navbar products link title': 'Продукты',
    'Navbar users link title': 'Пользователи',
    'Navbar console link title': 'Консоль',
    'Navbar info link title': 'Информация',
    'Navbar logout title': 'Выход',

    'Developer console title': 'Консоль разработчика',
    'SQL requests section': 'SQL запросы',
    'SQL request': 'SQL запрос',
    'SQL request submit button': 'Выполнить',

    'Info title': 'Информация',
    'Info page contacts heading': 'Контакты',
    'Info page contacts text': '''В случае проблем с сайтом, наличии предложений и просто желании поболтать, вы можете написать нам письмо.''',
    'Info page email title': 'Email',
    'Info page email address': 'archidevil52@gmail.com',
    'Info page telegram title': 'Telegram',
    'Info page telegram address': '@archidevil',
    'Info page copyrights heading': 'Информация о лицензиях',
    'Info page copyrights text': '''Данный проект не содержит никакой обязательной лицензии. Вся функциональность предоставляется "как есть".
    Вы используете проект на свой страх и риск. Мы не несем никакой ответственности в случае возникновения проблем, вызванных неправильным использованием проекта.''',
    'Info Freepik text': '''Вся графика на этом сайте взята с Freepick.com.
    Как того требует лицензия для использования графических материалов, мы предоставляем копирайты дизайнеров, выполнивших работы ниже.''',

    'Internal error 500 message': 'Произошла внутренняя ошибка сервера. Приносим свои извинения, мы постараемся исправить её как можно скорее.',
    'Sentry title': 'Похоже у нас проблемы.',
    'Sentry subtitle': 'Команда уже получила уведомление.',
    'Sentry subtitle2': 'Если вы хотите помочь, то заполните пару полей ниже.',
    'Sentry label name': 'Имя',
    'Sentry label email': 'Email',
    'Sentry label comments': 'Что случилось?',
    'Sentry label close': 'Закрыть',
    'Sentry label submit': 'Отправить',
    'Sentry error generic': 'Произошла ошибка во время отправки. Попробуйте еще раз.',
    'Sentry error form entry': 'Некоторые поля заполнены некорректно. Исправьте ошибки и попробуйте еще раз.',
    'Sentry success message': 'Ваш отчет был отправлен. Спасибо!',

    'Login title': 'Вход',
    'Login username placeholder': 'Имя пользователя',
    'Login password placeholder': 'Пароль',
    'Login remember me title': 'Запомнить меня',
    'Login login button': 'Войти',
    'Login login with vk button': 'Войти с помощью Vk',

    'Login errors no user': 'Пользователь не найден',
    'Login errors no password': 'У этого пользователя нет пароля. Вы входили через Vk?',
    'Login errors incorrect password': 'Неправильный пароль',
    'Login errors vk error': 'Внутренняя ошибка',

    'Packing report title': 'отчет для фасовки',
    'Packing report selector title': 'Количество дней в ряд',
    'Packing report selector 1': '1 день',
    'Packing report selector 2': '2 дня',
    'Packing report selector 3': '3 дня',
    'Packing report selector 4': '4 дня',
    'Packing report selector 5': '5 дней',
    'Packing report selector 6': '6 дней',
    'Packing report day title': 'День',
    'Packing report name column title': 'Продукт',
    'Packing report persons suffix': 'чел',
    'Packing report pieces suffix': 'шт',
    'Packing report grams suffix': 'г',

    'Shopping report title': 'список покупок',
    'Shopping report card header': 'Что дальше?',
    'Shopping report card text': '''Лучший способ работы с этим отчетом это распечатать его.
    Распечатайте список и возьмите с собой в магазин.
    Так вы ничего не забудете. При печати мы оставили вам поля для заметок, если вдруг что-то пойдет не по плану.''',
    'Shopping report print card button': 'Напечатать',
    'Shopping report name title': 'Продукт',
    'Shopping report mass title': 'Масса',
    'Shopping report notes title': 'Заметки',
    'Shopping report grams suffix': 'г',
    'Shopping report pieces suffix': 'шт',

    'Users title': 'Пользователи',
    'Users add new button': 'Добавить',
    'Users id title': '#',
    'Users login title': 'Логин',
    'Users name title': 'Отображаемое имя',
    'Users password title': 'Пароль?',
    'Users group title': 'Группа',
    'Users type title': 'Тип',
    'Users last login title': 'Вход',
    'Users actions title': 'Действия',
    'Users remove button title': 'Удалить',
    'Users edit button title': 'Редактировать',
    'Users delete user modal title': 'Удалить пользователя?',
    'Users delete user modal text': 'Внимание: это действие нельзя отменить!',
    'Users delete user modal text2': 'Вы точно хотите удалить этого пользователя?',
    'Users delete user modal delete': 'Удалить',
    'Users delete user modal close': 'Закрыть',

    'User edit login title': 'Логин',
    'User edit password title': 'Пароль',
    'User edit access group title': 'Группа',
    'User edit invalid login': 'Поле не должно быть пустым',
    'User edit login placeholder': 'Логин',
    'User edit invalid password': 'Поле не должно быть пустым',
    'User edit password placeholder': 'Пароль',
    'User edit add user title': 'Добавить пользователя',
    'User edit edit user title': 'Редактировать пользователя',
    'User edit add button': 'Добавить',
    'User edit edit button': 'Применить',
    'User edit close button': 'Закрыть',
    'User edit error empty login': 'Пустой логин',
    'User edit error empty password': 'Пустой пароль',
    'User edit error empty group': 'Пустая группа',
    'User edit error wrong group': 'Некорректная группа',
    'User edit error existing login': 'Пользователь с таким логином уже существует',

    'Trips edit title': 'Редактировать поход',
    'Trips edit edit button': 'Применить',
    'Trips edit close button': 'Закрыть',
    'Trips add title': 'Создать поход',
    'Trips add edit button': 'Создать',
    'Trips edit title field': 'Название',
    'Trips edit title placeholder': 'Введите название',
    'Trips edit error empty title': 'Поле не должно быть пустым',
    'Trips edit dates field': 'Даты похода',
    'Trips edit groups config section': 'Конфигурация групп',
    'Trips edit groups field': 'Сколько групп участвует?',
    'Trips edit groups description': 'Группа людей это одна группа, где все едят из одного котелка.',
    'Trips edit groups count 1': '1 группа',
    'Trips edit groups count 2': '2 группы',
    'Trips edit groups count 3': '3 группы',
    'Trips edit groups count 4': '4 группы',
    'Trips edit groups count 5': '5 групп',
    'Trips edit group prefix': 'Группа',
    'Trips edit error group count': 'Введите целое число больше 0',
    'Trips edit archive button': 'Архивировать',

    'Trips edit error incorrect name': 'Некорректное имя',
    'Trips edit error incorrect groups': 'Некорректная информация о группах',
    'Trips edit error incorrect dates': 'Некорректные даты',

    'Trips edit archive modal title': 'Архивировать поход?',
    'Trips edit archive modal text': 'Вы действительно хотите поместить этот поход в архив?',
    'Trips edit archive modal archive button': 'Архивировать',
    'Trips edit archive modal close button': 'Закрыть',

    'Products title': 'Продукты',
    'Products card header': 'Чего-то не хватает?',
    'Products card text': '''Если вы не можете найти что-то в базе данных, то всегда можно добавить свой продукт самостоятельно.
    Нужно будет только заполнить информацию о пищевой ценности.''',
    'Products edit modal add button': 'Добавить',
    'Products edit modal add title': 'Добавить продукт',
    'Products error incorrect name': 'Некорретное имя',
    'Products error incorrect calories': 'Некорректное количество калорий',
    'Products error incorrect proteins': 'Некорретное количество белков',
    'Products error incorrect fats': 'Некорретное количество жиров',
    'Products error incorrect carbs': 'Некорретное количество углеводов',
    'Products error incorrect grams': 'Некорретное количество грамм на штуку',

    'Meals breakfast title': 'Завтрак',
    'Meals lunch title': 'Обед',
    'Meals dinner title': 'Ужин',
    'Meals snacks title': 'Перекусы',

    'Monday dp': 'Пн',
    'Tuesday dp': 'Вт',
    'Wednesday dp': 'Ср',
    'Thursday dp': 'Чт',
    'Friday dp': 'Пт',
    'Saturday dp': 'Сб',
    'Sunday dp': 'Вс',
    'January dp': 'Январь',
    'February dp': 'Февраль',
    'March dp': 'Март',
    'April dp': 'Апрель',
    'May dp': 'Май',
    'June dp': 'Июнь',
    'July dp': 'Июль',
    'August dp': 'Август',
    'September dp': 'Сентябрь',
    'October dp': 'Октябрь',
    'November dp': 'Ноябрь',
    'December dp': 'Декабрь',

    'CSV name': 'Продукт',
    'CSV day': 'День',
    'CSV meal': 'Прием пищи',
    'CSV mass': 'Масса на чел',
    'CSV cals': 'Калории',
}
