image: python:3.7

pipelines:
  branches:
    master:
      - step:
          name: 'Run tests'
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python -m pytest
      - step:
          name: Build and push to Heroku test environment
          deployment: test
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python setup.py sdist
            - pipe: atlassian/heroku-deploy:1.1.4
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $TEST_HEROKU_APP_NAME
                ZIP_FILE: 'dist/trips_organizer-0.3.tar.gz'
  pull-requests:
    feature/*:
      - step:
          name: 'Run tests'
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - python -m pytest
  custom:
    deploy-to-prod:
      - step:
          name: 'Deploy to production environment'
          deployment: production
          caches:
            - pip
          script:
              - pip install -r requirements.txt
              - python setup.py sdist
              - pipe: atlassian/heroku-deploy:1.1.4
                variables:
                  HEROKU_API_KEY: $HEROKU_API_KEY
                  HEROKU_APP_NAME: $PROD_HEROKU_APP_NAME
                  ZIP_FILE: 'dist/trips_organizer-0.3.tar.gz'
