version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    links:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      SERVER_NAME: ${SERVER_NAME}
      VK_APP_SECRET: ${VK_APP_SECRET}
      VK_CLIENT_ID: ${VK_CLIENT_ID}
    restart: on-failure

  # do not forget to add certificate updating each day or week into cron
  # with command like:
  # 0 9 * * 2 docker container exec trips-proxy-1 acme-nginx -d <domain>
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    volumes:
      - /root/nginx-vol/:/etc/ssl/private/
    restart: on-failure

volumes:
  postgres_data:
    driver: local
